### ISSUE TITLE
launching the environment

### ISSUE THREAD

**Issue by richardcevans** [RWaltersMA/OracleCDC2Mongo#1]
Hey Rob, thanks for this write-up!  To launch the container I had to run the following:

``docker-compose up -d --build`` 

That command was in your Mongo blog post but here in the README as ``docker-compose up -d build``

If I ran that command I received the following error:

``ERROR: No such service: build``

**Comment by RWaltersMA** [comment]
thank you for catching that! I changed the readme file.
